version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Melkoroth"
    assignees:
      - "Melkoroth"
    ignore:
      - dependency-name: "boto3"
        versions: ["<1.20.0"]
