
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Despliegue automático de FastAPI en AWS Lambda usando Mangum

Resources:
  FastAPIFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: ./
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - PolicyName: DynamoDBLeastPrivilegePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource: 
                  - arn:aws:dynamodb:us-east-1:${AWS::AccountId}:table/MyRAGArchTable
      Environment:
        Variables:
          STAGE: dev
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
