on:
  workflow_dispatch:


name: Deploy to AWS Lambda

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Configurar AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Instalar dependencias optimizadas
        run: |
          pip install --target . --prefer-binary -r requirements.txt

      - name: Empaquetar y desplegar en AWS Lambda
        run: |
          zip -r deployment_package.zip . -x '*.git*'
          aws lambda update-function-code --function-name MedicalRAG --zip-file fileb://deployment_package.zip
