name: CI/CD for Medical-RAGArch-System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Clear pip cache
        run: |
          pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Start FastAPI server
        run: |
          cd .  # Se queda en la raíz del repositorio
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10  # Espera a que el servidor se inicie

      - name: Test with Pytest
        run: |
          python -m pip install httpx  # Instala HTTPX temporalmente
          pytest tests --disable-warnings

  deploy-to-aws-lambda:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache SAM Build Artifacts
        uses: actions/cache@v4
        with:
          path: .aws-sam/build
          key: ${{ runner.os }}-sam-${{ hashFiles('**/*.py') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-sam-

      - name: Cache AWS SAM CLI
        uses: actions/cache@v4
        with:
          path: ~/.aws-sam-cli
          key: ${{ runner.os }}-samcli-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-samcli-

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Run Tests Again
        run: |
          pytest tests

      - name: Package and Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sam build
          sam package --output-template-file packaged.yaml --s3-bucket ${{ secrets.S3_BUCKET_NAME }}
          sam deploy --template-file packaged.yaml --stack-name medical-ragarch-system --capabilities CAPABILITY_IAM
