name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Instalar Hugging Face CLI y actualizarla
      run: |
        pip install --upgrade huggingface_hub
        huggingface-cli login --token ${{ secrets.HF_TOKEN }}

    - name: Crear el Space en Hugging Face
      run: |
        huggingface-cli repo create Melkoroth/Medical-RAGArch-System --type space --space-sdk docker --yes

    - name: Subir contenido al Space
      run: |
        huggingface-cli repo upload Melkoroth/Medical-RAGArch-System --recursive --commit-message "Deploy automático"
